config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'eposts#index'
  resources 'topics'
  resources 'eposts'
  namespace :admin do
    resources :topics
    resources 'eposts'
  end
  get 'admin' => 'admin/topics#index', as: :admin
  get 'about' => 'st_pages#about', as: :about
  get 'log' => 'st_pages#log', as: :log

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/epost.rb
class Epost < ActiveRecord::Base
  validates :title, :content, :tag, :presence => true
  has_many :comments 
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  scope :list_filter, ->(tag){where(tag: tag) if tag.present?}
  
  def self.list_filter2(tag)
    if tag.present?    
      where(tag: tag)
    else
      all
    end
  end
  validates :title, :context, :tag, :presence => true
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :authenticate_user!
end

app/controllers/admin/eposts_controller.rb
class Admin::EpostsController < Admin::BaseController
  def index
    @eposts = Epost.all
  end
  def show
    @epost = Epost.find(params[:id])
  end
  def new
    @epost = Epost.new
  end
  def create
    @epost = Epost.new(epost_params)
    if @epost.save
      redirect_to admin_eposts_url
    else
      render :new
    end
  end
  def edit
    @epost = Epost.find(params[:id])
  end
  def update
    @epost = Epost.find(params[:id])
    if @epost.update(epost_params)
      redirect_to admin_eposts_url
    else
      render :edit
    end
  end
  def destroy
    @epost = Epost.find(params[:id])
    @epost.destroy
    
    redirect_to admin_eposts_url
  end
  
  private
  def epost_params
    params.require(:epost).permit(:title, :content, :tag)
  end
end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < Admin::BaseController
  def index
    @topics = Topic.all
    @st_id = 0
  end
  def show
    @topic = Topic.find(params[:id])
  end
  def new
    @topic = Topic.new
  end
  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      redirect_to admin_topics_url
    else
      render :new
    end
  end
  def edit
    @topic = Topic.find(params[:id])
  end
  def update
    @topic = Topic.find(params[:id])
    if @topic.update(topic_params)
      redirect_to admin_topics_url
    else
      render :edit
    end
  end
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    
    redirect_to admin_topics_url 
  end
 
  private
  def topic_params
    params.require(:topic).permit(:title, :context, :tag)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :comment_find
  def new
    @comment = @topic.comments.new
  end
  def create
    @comment = @topic.comments.new(comment_params)
    if @comment.save
      redirect_to topic_url(@topic)
    else
      render :new
    end
  end
  
  private
  def comment_params
    params.require(:comment).permit(:title, :content)
  end
  def comment_find
    @topic = Topic.find(params[:topic_id])

  end
end

app/controllers/eposts_controller.rb
class EpostsController < ApplicationController
  def index
    @eposts = Epost.all
    @sort_id = 0
  end
  def show
    @epost = Epost.find(params[:id])
  end
  
  private
  def epost_params
    params.require(:epost).permit(:title, :content, :tag)
  end
end

app/controllers/st_pages_controller.rb
class StPagesController < ApplicationController
  def about
  end
  def log
    @log = Topic.where(tag: :log)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.list_filter(params[:tag])
    @sort_id = 0
  end
  def show
    @topic = Topic.find(params[:id])
    @comments = @topic.comments
  end

  private
  def topic_params
    params.require(:topic).permit(:title, :context, :tag)
  end
end

app/helpers/admin/eposts_helper.rb
module Admin::EpostsHelper
end

app/helpers/admin/topics_helper.rb
module Admin::TopicsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def mkdown_to_html(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    markdown = markdown.render(text)
  end
  def st_id
    @sort_id = @sort_id + 1
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/eposts_helper.rb
module EpostsHelper
end

app/helpers/st_pages_helper.rb
module StPagesHelper
  def mkdown_to_html(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    markdown = markdown.render(text)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/admin/common/_editor.html.erb
<!--TEST時對照用-->
<textarea class="form-control" rows="10" data-uk-htmleditor="{markdown:true,mode:'tab'}"></textarea>

app/views/admin/common/_menu.html.erb
  <p><h3 id="part_1_">管理項目</h3>
  <div id="submenu">
    <%= link_to('文章管理',admin_topics_url) %><br>
    <%= link_to('日記管理',admin_eposts_url) %><br>
  </div>

app/views/admin/eposts/_form.html.erb
<h3>日記</h3>
<%= form_for [:admin, @epost] do |f| %>
  Title: <%= f.text_field :title %>
  Tag: <%= f.text_field :tag %><br>
  <%= f.text_area :content, size: "120x20", :class => 'form-control', :'data-uk-htmleditor' => "{markdown:true,mode:'tab'}" %><br>
  <%= f.submit 'sumbit' %>
<span style="float:right"><%= link_to('Back',admin_eposts_url) %></span>
<% end %>

app/views/admin/eposts/edit.html.erb
<%= render :partial =>'form' %>

app/views/admin/eposts/index.html.erb
<% content_for :banner do %>
  <h3 id="part_1_">執行動作</h3>
  <div id="submenu">
    <%= link_to('新增日記',new_admin_epost_path) %>
  </div>
  <%= render :partial =>'admin/common/menu' %>
<% end %>

<% @eposts.each do |f| %>
  <%= f.title %> | Action =>
  <%= link_to('Edit', edit_admin_epost_path(f)) %>
  <%= link_to('delete', admin_epost_url(f), :method => 'delete')%><br>
<% end %>

app/views/admin/eposts/new.html.erb
<%= render :partial =>'form' %>

app/views/admin/topics/_form.html.erb
<h3>學習歷程</h3>
<%= form_for [:admin, @topic] do |f| %>
  Title: <%= f.text_field :title %>
  Tag: <%= f.text_field :tag %><br>
<%= f.text_area :context, size: "120x20", :class => 'form-control', :'data-uk-htmleditor' => "{markdown:true,mode:'tab'}" %><br>
  <%= f.submit 'sumbit' %>
<span style="float:right"><%= link_to('Back',admin_topics_url) %></span>
<% end %>

app/views/admin/topics/edit.html.erb
<%= render :partial =>'form' %>

app/views/admin/topics/index.html.erb
<% content_for :banner do %>
  <h3 id="part_1_">執行動作</h3>
  <div id="submenu">
    <%= link_to('新增文章',new_admin_topic_path) %>
  </div>
  <%= render :partial =>'admin/common/menu' %>
<% end %>

<% @topics.each do |f| %>
  <%= f.title %> | Action =>
  <%= link_to('Edit', edit_admin_topic_path(f)) %>
  <%= link_to('delete', admin_topic_url(f), :method => 'delete')%><br>
<% end %>

app/views/admin/topics/new.html.erb
<%= render :partial =>'form' %>

app/views/comments/_form.html.erb
<h3>Comment</h3>
<%= form_for [@topic, @comment] do |f| %>
  Title: <%= f.text_field :title %>
  <%= f.text_area :content, size: "120x20" %><br>
  <%= f.submit 'sumbit' %>
<% end %>

app/views/comments/new.html.erb
<%= render :partial => 'form' %>

app/views/common/_bot.html.erb
  <h4 id="part_1_">這是選單</h3>
  <div id="submenu">
    <!--topics(tag篩選)-->
    <h6><%= link_to("Rails學習歷程", topics_url(:tag => '101')) %></h6>
    <!--etposts(多重篩選)-->
    <h6><%= link_to("我的美食日記", eposts_url) %></h6>
    <!--stpage(route)-->
    <h6><%= link_to("站台開發Log", log_url) %></h6>
    <!--stpage(route)-->
    <h6><%= link_to("關於站長", about_url) %></h6>
  </div>

app/views/common/_footer.html.erb
<div class="footer">
	<div class="container">
	<p>
	<a href="#">Rails 0+B</a> | Copyright©2014 <a href="#">JRD</a>. All Rights Reserved.<br>
	本網頁樣式來自 CouchDB: The Definitive Guide。
	</p>
</div>
</div>

app/views/common/_head.html.erb
<div class="page_header">
    <h1 class="logo">
	<%= controller.class.to_s.include?('Admin')? link_to('Rails Admin', admin_topics_url) : link_to('Rails Eat', '/' )%>
      	<span>使用 Rails 3.2 及 Ruby 1.9.3</span>
    </h1>
    <div class="search_box">
        <form class="search" action="http://www.google.com/search">
        <!--<input type="hidden" value="ihower.tw/rails3" name="as_sitesearch">-->
        <input class="search_field" type="text" value="" name="as_q">
        <input class="search_btn" type="submit" value="Search">
        </form>
    </div>
</div>
<div class="notice">
    <p class="inner info_bubble">
        記錄Rails學習過程與分享，若您發現文章中有任何錯誤，歡迎來信給我，謝謝。
    </p>
</div>

app/views/eposts/index.html.erb
<% content_for :banner do %>
  <h4 id="part_1_">文章分類</h4>
  <div id="submenu">
    <h6><%= link_to("高雄") %></h6>
  </div><P>
  <%= render :partial =>'common/bot' %>
<% end %>

<% @eposts.each do |f| %>
  <%= st_id %>. :: 
  <%= link_to(f.title, epost_path(f)) %><br>
<% end %>

app/views/eposts/show.html.erb
<%= mkdown_to_html(@epost.content).html_safe %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Rails Log</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
	<div class="container">
		<%= render :partial => "common/head" %>
		<div class="inner wrap">
			<div class="sidebar">
				<%= yield :banner %>
			</div>
			<div class="content body">
			<%= yield %>
			</div>
		</div>
	</div>
	<%= render :partial => "common/footer" %>
</body>
</html>

app/views/st_pages/about.html.erb
<% content_for :banner do %>
  <%= render :partial =>'common/bot' %>
<% end %>
<%
html = <<HTML
**aaa**
> aadfa
HTML
%>
<%= mkdown_to_html(html).html_safe %>

app/views/st_pages/log.html.erb
<% content_for :banner do %>
  <%= render :partial =>'common/bot' %>
<% end %>
<% @log.each do |f| %>
 <%= mkdown_to_html(f.context).html_safe %>
<% end %>

app/views/topics/index.html.erb
<% content_for :banner do %>
  <h4 id="part_1_">文章分類</h4>
  <div id="submenu">
    <h6><%= link_to("Rails101 交流", topics_path(:tag => '101')) %></h6>
    <h6><%= link_to("專案開發心得", topics_path(:tag => 'project')) %></h6>
  </div><P>
  <%= render :partial =>'common/bot' %>
<% end %>

<% @topics.each do |f| %>
  <%= st_id %>. :: 
  <%= link_to(f.title, topic_path(f)) %><br>
<% end %>

app/views/topics/show.html.erb
<% content_for :banner do %>
  <div id="submenu">
    <h4><%= link_to("返回上層",topics_url) %></h4>
  </div><P>
<% end %>
<%= mkdown_to_html(@topic.context).html_safe %>
<% @comments.each do |msg| %>
<%= msg.title %>
<%= msg.content %>
<% end %>
<h4><%= link_to("Comment",new_topic_comment_path(@topic)) %></h4>